name: get advisories

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
    - name: install cargo deny
      run: cargo install --locked cargo-deny
    - name: check advisories
      run: cargo deny check advisories
