name: get advisories

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
    - name: install cargo deny
      run: cargo install --locked cargo-deny
    - name: check advisories
      run: cargo deny check advisories
