name: build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'src/*'
      - 'Cargo.toml'
      - 'Cargo.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - name: Build
      run: cargo build --release
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          target/release
          !target/release/.fingerprint
          !target/release/deps
          !target/release/build
          !target/release/examples
          !target/release/incremental
          !target/release/.cargo-lock
          !target/release/*.d
