name: clippy

on:
  push:
    paths:
      - '.github/workflows/clippy.yml'
      - 'src/*'
      - 'Cargo.toml'
      - 'Cargo.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - name: add cargo clippy
      run: rustup component add clippy
    - name: test
      run: cargo clippy
